-- BCAMOVIES+ Community setup
create table if not exists public.community_messages (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 display_name text not null default 'Movie Fan',
 message text not null check (char_length(message) between 1 and 1000),
 type text not null default 'chat' check (type in ('chat','request')),
 created_at timestamptz not null default now()
);
create table if not exists public.polls (
 id bigint generated by default as identity primary key,
 question text not null,
 options jsonb not null,
 created_at timestamptz not null default now()
);
create table if not exists public.poll_votes (
 poll_id bigint not null references public.polls(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade,
 option_index int not null,
 created_at timestamptz not null default now(),
 primary key (poll_id,user_id)
);
alter table public.community_messages enable row level security;
alter table public.polls enable row level security;
alter table public.poll_votes enable row level security;
drop policy if exists "Public read community" on public.community_messages;
drop policy if exists "Users post community" on public.community_messages;
drop policy if exists "Users delete own messages" on public.community_messages;
drop policy if exists "Owner delete any message" on public.community_messages;
drop policy if exists "Public read polls" on public.polls;
drop policy if exists "Owner manages polls" on public.polls;
drop policy if exists "Users read votes" on public.poll_votes;
drop policy if exists "Users vote" on public.poll_votes;
drop policy if exists "Users update vote" on public.poll_votes;
create policy "Public read community" on public.community_messages for select to anon,authenticated using(true);
create policy "Users post community" on public.community_messages for insert to authenticated with check(auth.uid()=user_id);
create policy "Users delete own messages" on public.community_messages for delete to authenticated using(auth.uid()=user_id);
create policy "Owner delete any message" on public.community_messages for delete to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='jonathanspollard11@gmail.com');
create policy "Public read polls" on public.polls for select to anon,authenticated using(true);
create policy "Owner manages polls" on public.polls for all to authenticated using(lower(coalesce(auth.jwt()->>'email',''))='jonathanspollard11@gmail.com') with check(lower(coalesce(auth.jwt()->>'email',''))='jonathanspollard11@gmail.com');
create policy "Users read votes" on public.poll_votes for select to authenticated using(true);
create policy "Users vote" on public.poll_votes for insert to authenticated with check(auth.uid()=user_id);
create policy "Users update vote" on public.poll_votes for update to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
